ALTER TABLE users ADD COLUMN  address  VARCHAR NULL;
ALTER TABLE users ADD COLUMN  phone  VARCHAR NULL;
ALTER TABLE users ADD COLUMN  imagePath  VARCHAR NULL;
ALTER TABLE users ADD COLUMN  enabled  boolean NULL;