// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Products.proto
// Protobuf Java Version: 4.28.1

package com.lkgroup.ecommerce.protobuf.userproto;

public final class ProductProtos {
  private ProductProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      ProductProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ecommerce.ProductRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string productName = 1;</code>
     * @return The productName.
     */
    java.lang.String getProductName();
    /**
     * <code>string productName = 1;</code>
     * @return The bytes for productName.
     */
    com.google.protobuf.ByteString
        getProductNameBytes();
  }
  /**
   * Protobuf type {@code ecommerce.ProductRequest}
   */
  public static final class ProductRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ecommerce.ProductRequest)
      ProductRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        ProductRequest.class.getName());
    }
    // Use ProductRequest.newBuilder() to construct.
    private ProductRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProductRequest() {
      productName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.internal_static_ecommerce_ProductRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.internal_static_ecommerce_ProductRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest.class, com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest.Builder.class);
    }

    public static final int PRODUCTNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object productName_ = "";
    /**
     * <code>string productName = 1;</code>
     * @return The productName.
     */
    @java.lang.Override
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productName_ = s;
        return s;
      }
    }
    /**
     * <code>string productName = 1;</code>
     * @return The bytes for productName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(productName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, productName_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(productName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, productName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest)) {
        return super.equals(obj);
      }
      com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest other = (com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest) obj;

      if (!getProductName()
          .equals(other.getProductName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getProductName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ecommerce.ProductRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ecommerce.ProductRequest)
        com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.internal_static_ecommerce_ProductRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.internal_static_ecommerce_ProductRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest.class, com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest.Builder.class);
      }

      // Construct using com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        productName_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.internal_static_ecommerce_ProductRequest_descriptor;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest getDefaultInstanceForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest build() {
        com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest buildPartial() {
        com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest result = new com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.productName_ = productName_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest) {
          return mergeFrom((com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest other) {
        if (other == com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest.getDefaultInstance()) return this;
        if (!other.getProductName().isEmpty()) {
          productName_ = other.productName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                productName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object productName_ = "";
      /**
       * <code>string productName = 1;</code>
       * @return The productName.
       */
      public java.lang.String getProductName() {
        java.lang.Object ref = productName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productName = 1;</code>
       * @return The bytes for productName.
       */
      public com.google.protobuf.ByteString
          getProductNameBytes() {
        java.lang.Object ref = productName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productName = 1;</code>
       * @param value The productName to set.
       * @return This builder for chaining.
       */
      public Builder setProductName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        productName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string productName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductName() {
        productName_ = getDefaultInstance().getProductName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string productName = 1;</code>
       * @param value The bytes for productName to set.
       * @return This builder for chaining.
       */
      public Builder setProductNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        productName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ecommerce.ProductRequest)
    }

    // @@protoc_insertion_point(class_scope:ecommerce.ProductRequest)
    private static final com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest();
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductRequest>
        PARSER = new com.google.protobuf.AbstractParser<ProductRequest>() {
      @java.lang.Override
      public ProductRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProductRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lkgroup.ecommerce.protobuf.userproto.ProductProtos.ProductRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_ProductRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ecommerce_ProductRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Products.proto\022\tecommerce\"%\n\016ProductRe" +
      "quest\022\023\n\013productName\030\001 \001(\tB9\n(com.lkgrou" +
      "p.ecommerce.protobuf.userprotoB\rProductP" +
      "rotosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ecommerce_ProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ecommerce_ProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ecommerce_ProductRequest_descriptor,
        new java.lang.String[] { "ProductName", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
