// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Role.proto
// Protobuf Java Version: 4.28.1

package com.lkgroup.ecommerce.protobuf.userproto;

public final class RoleProtos {
  private RoleProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      RoleProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoleResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ecommerce.RoleResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>repeated string permissions = 4;</code>
     * @return A list containing the permissions.
     */
    java.util.List<java.lang.String>
        getPermissionsList();
    /**
     * <code>repeated string permissions = 4;</code>
     * @return The count of permissions.
     */
    int getPermissionsCount();
    /**
     * <code>repeated string permissions = 4;</code>
     * @param index The index of the element to return.
     * @return The permissions at the given index.
     */
    java.lang.String getPermissions(int index);
    /**
     * <code>repeated string permissions = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the permissions at the given index.
     */
    com.google.protobuf.ByteString
        getPermissionsBytes(int index);
  }
  /**
   * Protobuf type {@code ecommerce.RoleResponse}
   */
  public static final class RoleResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ecommerce.RoleResponse)
      RoleResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        RoleResponse.class.getName());
    }
    // Use RoleResponse.newBuilder() to construct.
    private RoleResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RoleResponse() {
      id_ = "";
      name_ = "";
      description_ = "";
      permissions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_RoleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_RoleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.class, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERMISSIONS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList permissions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string permissions = 4;</code>
     * @return A list containing the permissions.
     */
    public com.google.protobuf.ProtocolStringList
        getPermissionsList() {
      return permissions_;
    }
    /**
     * <code>repeated string permissions = 4;</code>
     * @return The count of permissions.
     */
    public int getPermissionsCount() {
      return permissions_.size();
    }
    /**
     * <code>repeated string permissions = 4;</code>
     * @param index The index of the element to return.
     * @return The permissions at the given index.
     */
    public java.lang.String getPermissions(int index) {
      return permissions_.get(index);
    }
    /**
     * <code>repeated string permissions = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the permissions at the given index.
     */
    public com.google.protobuf.ByteString
        getPermissionsBytes(int index) {
      return permissions_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, description_);
      }
      for (int i = 0; i < permissions_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, permissions_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, description_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < permissions_.size(); i++) {
          dataSize += computeStringSizeNoTag(permissions_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPermissionsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse)) {
        return super.equals(obj);
      }
      com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse other = (com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getPermissionsList()
          .equals(other.getPermissionsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      if (getPermissionsCount() > 0) {
        hash = (37 * hash) + PERMISSIONS_FIELD_NUMBER;
        hash = (53 * hash) + getPermissionsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ecommerce.RoleResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ecommerce.RoleResponse)
        com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_RoleResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_RoleResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.class, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.Builder.class);
      }

      // Construct using com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        name_ = "";
        description_ = "";
        permissions_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_RoleResponse_descriptor;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse getDefaultInstanceForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse build() {
        com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse buildPartial() {
        com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse result = new com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.description_ = description_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          permissions_.makeImmutable();
          result.permissions_ = permissions_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse) {
          return mergeFrom((com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse other) {
        if (other == com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.permissions_.isEmpty()) {
          if (permissions_.isEmpty()) {
            permissions_ = other.permissions_;
            bitField0_ |= 0x00000008;
          } else {
            ensurePermissionsIsMutable();
            permissions_.addAll(other.permissions_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensurePermissionsIsMutable();
                permissions_.add(s);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 3;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList permissions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensurePermissionsIsMutable() {
        if (!permissions_.isModifiable()) {
          permissions_ = new com.google.protobuf.LazyStringArrayList(permissions_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @return A list containing the permissions.
       */
      public com.google.protobuf.ProtocolStringList
          getPermissionsList() {
        permissions_.makeImmutable();
        return permissions_;
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @return The count of permissions.
       */
      public int getPermissionsCount() {
        return permissions_.size();
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @param index The index of the element to return.
       * @return The permissions at the given index.
       */
      public java.lang.String getPermissions(int index) {
        return permissions_.get(index);
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the permissions at the given index.
       */
      public com.google.protobuf.ByteString
          getPermissionsBytes(int index) {
        return permissions_.getByteString(index);
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @param index The index to set the value at.
       * @param value The permissions to set.
       * @return This builder for chaining.
       */
      public Builder setPermissions(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePermissionsIsMutable();
        permissions_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @param value The permissions to add.
       * @return This builder for chaining.
       */
      public Builder addPermissions(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePermissionsIsMutable();
        permissions_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @param values The permissions to add.
       * @return This builder for chaining.
       */
      public Builder addAllPermissions(
          java.lang.Iterable<java.lang.String> values) {
        ensurePermissionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, permissions_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPermissions() {
        permissions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 4;</code>
       * @param value The bytes of the permissions to add.
       * @return This builder for chaining.
       */
      public Builder addPermissionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensurePermissionsIsMutable();
        permissions_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ecommerce.RoleResponse)
    }

    // @@protoc_insertion_point(class_scope:ecommerce.RoleResponse)
    private static final com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse();
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoleResponse>
        PARSER = new com.google.protobuf.AbstractParser<RoleResponse>() {
      @java.lang.Override
      public RoleResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RoleResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoleResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RolesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ecommerce.RolesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ecommerce.RoleResponse content = 1;</code>
     */
    java.util.List<com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse> 
        getContentList();
    /**
     * <code>repeated .ecommerce.RoleResponse content = 1;</code>
     */
    com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse getContent(int index);
    /**
     * <code>repeated .ecommerce.RoleResponse content = 1;</code>
     */
    int getContentCount();
    /**
     * <code>repeated .ecommerce.RoleResponse content = 1;</code>
     */
    java.util.List<? extends com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponseOrBuilder> 
        getContentOrBuilderList();
    /**
     * <code>repeated .ecommerce.RoleResponse content = 1;</code>
     */
    com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponseOrBuilder getContentOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ecommerce.RolesResponse}
   */
  public static final class RolesResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ecommerce.RolesResponse)
      RolesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        RolesResponse.class.getName());
    }
    // Use RolesResponse.newBuilder() to construct.
    private RolesResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RolesResponse() {
      content_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_RolesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_RolesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse.class, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse.Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse> content_;
    /**
     * <code>repeated .ecommerce.RoleResponse content = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse> getContentList() {
      return content_;
    }
    /**
     * <code>repeated .ecommerce.RoleResponse content = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponseOrBuilder> 
        getContentOrBuilderList() {
      return content_;
    }
    /**
     * <code>repeated .ecommerce.RoleResponse content = 1;</code>
     */
    @java.lang.Override
    public int getContentCount() {
      return content_.size();
    }
    /**
     * <code>repeated .ecommerce.RoleResponse content = 1;</code>
     */
    @java.lang.Override
    public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse getContent(int index) {
      return content_.get(index);
    }
    /**
     * <code>repeated .ecommerce.RoleResponse content = 1;</code>
     */
    @java.lang.Override
    public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponseOrBuilder getContentOrBuilder(
        int index) {
      return content_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < content_.size(); i++) {
        output.writeMessage(1, content_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < content_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, content_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse)) {
        return super.equals(obj);
      }
      com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse other = (com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse) obj;

      if (!getContentList()
          .equals(other.getContentList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getContentCount() > 0) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContentList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ecommerce.RolesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ecommerce.RolesResponse)
        com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_RolesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_RolesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse.class, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse.Builder.class);
      }

      // Construct using com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (contentBuilder_ == null) {
          content_ = java.util.Collections.emptyList();
        } else {
          content_ = null;
          contentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_RolesResponse_descriptor;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse getDefaultInstanceForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse build() {
        com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse buildPartial() {
        com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse result = new com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse result) {
        if (contentBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            content_ = java.util.Collections.unmodifiableList(content_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
      }

      private void buildPartial0(com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse) {
          return mergeFrom((com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse other) {
        if (other == com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse.getDefaultInstance()) return this;
        if (contentBuilder_ == null) {
          if (!other.content_.isEmpty()) {
            if (content_.isEmpty()) {
              content_ = other.content_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContentIsMutable();
              content_.addAll(other.content_);
            }
            onChanged();
          }
        } else {
          if (!other.content_.isEmpty()) {
            if (contentBuilder_.isEmpty()) {
              contentBuilder_.dispose();
              contentBuilder_ = null;
              content_ = other.content_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contentBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getContentFieldBuilder() : null;
            } else {
              contentBuilder_.addAllMessages(other.content_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse m =
                    input.readMessage(
                        com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.parser(),
                        extensionRegistry);
                if (contentBuilder_ == null) {
                  ensureContentIsMutable();
                  content_.add(m);
                } else {
                  contentBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse> content_ =
        java.util.Collections.emptyList();
      private void ensureContentIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          content_ = new java.util.ArrayList<com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse>(content_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.Builder, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponseOrBuilder> contentBuilder_;

      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public java.util.List<com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse> getContentList() {
        if (contentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(content_);
        } else {
          return contentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public int getContentCount() {
        if (contentBuilder_ == null) {
          return content_.size();
        } else {
          return contentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse getContent(int index) {
        if (contentBuilder_ == null) {
          return content_.get(index);
        } else {
          return contentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public Builder setContent(
          int index, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.set(index, value);
          onChanged();
        } else {
          contentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public Builder setContent(
          int index, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.set(index, builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public Builder addContent(com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.add(value);
          onChanged();
        } else {
          contentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public Builder addContent(
          int index, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.add(index, value);
          onChanged();
        } else {
          contentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public Builder addContent(
          com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.add(builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public Builder addContent(
          int index, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.add(index, builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public Builder addAllContent(
          java.lang.Iterable<? extends com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse> values) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, content_);
          onChanged();
        } else {
          contentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public Builder removeContent(int index) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.remove(index);
          onChanged();
        } else {
          contentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.Builder getContentBuilder(
          int index) {
        return getContentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponseOrBuilder getContentOrBuilder(
          int index) {
        if (contentBuilder_ == null) {
          return content_.get(index);  } else {
          return contentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public java.util.List<? extends com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponseOrBuilder> 
           getContentOrBuilderList() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(content_);
        }
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.Builder addContentBuilder() {
        return getContentFieldBuilder().addBuilder(
            com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.Builder addContentBuilder(
          int index) {
        return getContentFieldBuilder().addBuilder(
            index, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .ecommerce.RoleResponse content = 1;</code>
       */
      public java.util.List<com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.Builder> 
           getContentBuilderList() {
        return getContentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.Builder, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponseOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponse.Builder, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RoleResponseOrBuilder>(
                  content_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ecommerce.RolesResponse)
    }

    // @@protoc_insertion_point(class_scope:ecommerce.RolesResponse)
    private static final com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse();
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RolesResponse>
        PARSER = new com.google.protobuf.AbstractParser<RolesResponse>() {
      @java.lang.Override
      public RolesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RolesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RolesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.RolesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreateRoleRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ecommerce.CreateRoleRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>repeated string permissions = 3;</code>
     * @return A list containing the permissions.
     */
    java.util.List<java.lang.String>
        getPermissionsList();
    /**
     * <code>repeated string permissions = 3;</code>
     * @return The count of permissions.
     */
    int getPermissionsCount();
    /**
     * <code>repeated string permissions = 3;</code>
     * @param index The index of the element to return.
     * @return The permissions at the given index.
     */
    java.lang.String getPermissions(int index);
    /**
     * <code>repeated string permissions = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the permissions at the given index.
     */
    com.google.protobuf.ByteString
        getPermissionsBytes(int index);
  }
  /**
   * Protobuf type {@code ecommerce.CreateRoleRequest}
   */
  public static final class CreateRoleRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ecommerce.CreateRoleRequest)
      CreateRoleRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        CreateRoleRequest.class.getName());
    }
    // Use CreateRoleRequest.newBuilder() to construct.
    private CreateRoleRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CreateRoleRequest() {
      name_ = "";
      description_ = "";
      permissions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_CreateRoleRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_CreateRoleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest.class, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERMISSIONS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList permissions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string permissions = 3;</code>
     * @return A list containing the permissions.
     */
    public com.google.protobuf.ProtocolStringList
        getPermissionsList() {
      return permissions_;
    }
    /**
     * <code>repeated string permissions = 3;</code>
     * @return The count of permissions.
     */
    public int getPermissionsCount() {
      return permissions_.size();
    }
    /**
     * <code>repeated string permissions = 3;</code>
     * @param index The index of the element to return.
     * @return The permissions at the given index.
     */
    public java.lang.String getPermissions(int index) {
      return permissions_.get(index);
    }
    /**
     * <code>repeated string permissions = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the permissions at the given index.
     */
    public com.google.protobuf.ByteString
        getPermissionsBytes(int index) {
      return permissions_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, description_);
      }
      for (int i = 0; i < permissions_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, permissions_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, description_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < permissions_.size(); i++) {
          dataSize += computeStringSizeNoTag(permissions_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPermissionsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest)) {
        return super.equals(obj);
      }
      com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest other = (com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getPermissionsList()
          .equals(other.getPermissionsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      if (getPermissionsCount() > 0) {
        hash = (37 * hash) + PERMISSIONS_FIELD_NUMBER;
        hash = (53 * hash) + getPermissionsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ecommerce.CreateRoleRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ecommerce.CreateRoleRequest)
        com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_CreateRoleRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_CreateRoleRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest.class, com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest.Builder.class);
      }

      // Construct using com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        description_ = "";
        permissions_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.internal_static_ecommerce_CreateRoleRequest_descriptor;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest getDefaultInstanceForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest build() {
        com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest buildPartial() {
        com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest result = new com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.description_ = description_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          permissions_.makeImmutable();
          result.permissions_ = permissions_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest) {
          return mergeFrom((com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest other) {
        if (other == com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.permissions_.isEmpty()) {
          if (permissions_.isEmpty()) {
            permissions_ = other.permissions_;
            bitField0_ |= 0x00000004;
          } else {
            ensurePermissionsIsMutable();
            permissions_.addAll(other.permissions_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                ensurePermissionsIsMutable();
                permissions_.add(s);
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 2;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList permissions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensurePermissionsIsMutable() {
        if (!permissions_.isModifiable()) {
          permissions_ = new com.google.protobuf.LazyStringArrayList(permissions_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <code>repeated string permissions = 3;</code>
       * @return A list containing the permissions.
       */
      public com.google.protobuf.ProtocolStringList
          getPermissionsList() {
        permissions_.makeImmutable();
        return permissions_;
      }
      /**
       * <code>repeated string permissions = 3;</code>
       * @return The count of permissions.
       */
      public int getPermissionsCount() {
        return permissions_.size();
      }
      /**
       * <code>repeated string permissions = 3;</code>
       * @param index The index of the element to return.
       * @return The permissions at the given index.
       */
      public java.lang.String getPermissions(int index) {
        return permissions_.get(index);
      }
      /**
       * <code>repeated string permissions = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the permissions at the given index.
       */
      public com.google.protobuf.ByteString
          getPermissionsBytes(int index) {
        return permissions_.getByteString(index);
      }
      /**
       * <code>repeated string permissions = 3;</code>
       * @param index The index to set the value at.
       * @param value The permissions to set.
       * @return This builder for chaining.
       */
      public Builder setPermissions(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePermissionsIsMutable();
        permissions_.set(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 3;</code>
       * @param value The permissions to add.
       * @return This builder for chaining.
       */
      public Builder addPermissions(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePermissionsIsMutable();
        permissions_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 3;</code>
       * @param values The permissions to add.
       * @return This builder for chaining.
       */
      public Builder addAllPermissions(
          java.lang.Iterable<java.lang.String> values) {
        ensurePermissionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, permissions_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPermissions() {
        permissions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 3;</code>
       * @param value The bytes of the permissions to add.
       * @return This builder for chaining.
       */
      public Builder addPermissionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensurePermissionsIsMutable();
        permissions_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ecommerce.CreateRoleRequest)
    }

    // @@protoc_insertion_point(class_scope:ecommerce.CreateRoleRequest)
    private static final com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest();
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateRoleRequest>
        PARSER = new com.google.protobuf.AbstractParser<CreateRoleRequest>() {
      @java.lang.Override
      public CreateRoleRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CreateRoleRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateRoleRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lkgroup.ecommerce.protobuf.userproto.RoleProtos.CreateRoleRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_RoleResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ecommerce_RoleResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_RolesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ecommerce_RolesResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_CreateRoleRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ecommerce_CreateRoleRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRole.proto\022\tecommerce\"R\n\014RoleResponse\022" +
      "\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013description" +
      "\030\003 \001(\t\022\023\n\013permissions\030\004 \003(\t\"9\n\rRolesResp" +
      "onse\022(\n\007content\030\001 \003(\0132\027.ecommerce.RoleRe" +
      "sponse\"K\n\021CreateRoleRequest\022\014\n\004name\030\001 \001(" +
      "\t\022\023\n\013description\030\002 \001(\t\022\023\n\013permissions\030\003 " +
      "\003(\tB6\n(com.lkgroup.ecommerce.protobuf.us" +
      "erprotoB\nRoleProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ecommerce_RoleResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ecommerce_RoleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ecommerce_RoleResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Permissions", });
    internal_static_ecommerce_RolesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ecommerce_RolesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ecommerce_RolesResponse_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_ecommerce_CreateRoleRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ecommerce_CreateRoleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ecommerce_CreateRoleRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "Permissions", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
