// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: User.proto
// Protobuf Java Version: 4.28.1

package com.lkgroup.ecommerce.protobuf.userproto;

public final class UsersProtos {
  private UsersProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      UsersProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ecommerce.UserResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string username = 3;</code>
     * @return The username.
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 3;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string address = 5;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 5;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string phone = 6;</code>
     * @return The phone.
     */
    java.lang.String getPhone();
    /**
     * <code>string phone = 6;</code>
     * @return The bytes for phone.
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>string imagePath = 7;</code>
     * @return The imagePath.
     */
    java.lang.String getImagePath();
    /**
     * <code>string imagePath = 7;</code>
     * @return The bytes for imagePath.
     */
    com.google.protobuf.ByteString
        getImagePathBytes();

    /**
     * <code>bool enabled = 8;</code>
     * @return The enabled.
     */
    boolean getEnabled();
  }
  /**
   * Protobuf type {@code ecommerce.UserResponse}
   */
  public static final class UserResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ecommerce.UserResponse)
      UserResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        UserResponse.class.getName());
    }
    // Use UserResponse.newBuilder() to construct.
    private UserResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserResponse() {
      id_ = "";
      name_ = "";
      username_ = "";
      email_ = "";
      address_ = "";
      phone_ = "";
      imagePath_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_UserResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_UserResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.class, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object username_ = "";
    /**
     * <code>string username = 3;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 3;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object address_ = "";
    /**
     * <code>string address = 5;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 5;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object phone_ = "";
    /**
     * <code>string phone = 6;</code>
     * @return The phone.
     */
    @java.lang.Override
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>string phone = 6;</code>
     * @return The bytes for phone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGEPATH_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object imagePath_ = "";
    /**
     * <code>string imagePath = 7;</code>
     * @return The imagePath.
     */
    @java.lang.Override
    public java.lang.String getImagePath() {
      java.lang.Object ref = imagePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imagePath_ = s;
        return s;
      }
    }
    /**
     * <code>string imagePath = 7;</code>
     * @return The bytes for imagePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImagePathBytes() {
      java.lang.Object ref = imagePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imagePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENABLED_FIELD_NUMBER = 8;
    private boolean enabled_ = false;
    /**
     * <code>bool enabled = 8;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, username_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, email_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(address_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, address_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phone_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, phone_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(imagePath_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, imagePath_);
      }
      if (enabled_ != false) {
        output.writeBool(8, enabled_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, username_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, email_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(address_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, address_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phone_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, phone_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(imagePath_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, imagePath_);
      }
      if (enabled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, enabled_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse)) {
        return super.equals(obj);
      }
      com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse other = (com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUsername()
          .equals(other.getUsername())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getPhone()
          .equals(other.getPhone())) return false;
      if (!getImagePath()
          .equals(other.getImagePath())) return false;
      if (getEnabled()
          != other.getEnabled()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (37 * hash) + IMAGEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getImagePath().hashCode();
      hash = (37 * hash) + ENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnabled());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ecommerce.UserResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ecommerce.UserResponse)
        com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_UserResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_UserResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.class, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.Builder.class);
      }

      // Construct using com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        name_ = "";
        username_ = "";
        email_ = "";
        address_ = "";
        phone_ = "";
        imagePath_ = "";
        enabled_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_UserResponse_descriptor;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse getDefaultInstanceForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse build() {
        com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse buildPartial() {
        com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse result = new com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.username_ = username_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.email_ = email_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.address_ = address_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.phone_ = phone_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.imagePath_ = imagePath_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.enabled_ = enabled_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse) {
          return mergeFrom((com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse other) {
        if (other == com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getImagePath().isEmpty()) {
          imagePath_ = other.imagePath_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.getEnabled() != false) {
          setEnabled(other.getEnabled());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                username_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                address_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                phone_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                imagePath_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                enabled_ = input.readBool();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 3;</code>
       * @return The username.
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 3;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 3;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        username_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        username_ = getDefaultInstance().getUsername();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string username = 3;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        username_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 5;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        address_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        address_ = getDefaultInstance().getAddress();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        address_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>string phone = 6;</code>
       * @return The phone.
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phone = 6;</code>
       * @return The bytes for phone.
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phone = 6;</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        phone_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        phone_ = getDefaultInstance().getPhone();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 6;</code>
       * @param value The bytes for phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        phone_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object imagePath_ = "";
      /**
       * <code>string imagePath = 7;</code>
       * @return The imagePath.
       */
      public java.lang.String getImagePath() {
        java.lang.Object ref = imagePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imagePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string imagePath = 7;</code>
       * @return The bytes for imagePath.
       */
      public com.google.protobuf.ByteString
          getImagePathBytes() {
        java.lang.Object ref = imagePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imagePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imagePath = 7;</code>
       * @param value The imagePath to set.
       * @return This builder for chaining.
       */
      public Builder setImagePath(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        imagePath_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string imagePath = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearImagePath() {
        imagePath_ = getDefaultInstance().getImagePath();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string imagePath = 7;</code>
       * @param value The bytes for imagePath to set.
       * @return This builder for chaining.
       */
      public Builder setImagePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        imagePath_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private boolean enabled_ ;
      /**
       * <code>bool enabled = 8;</code>
       * @return The enabled.
       */
      @java.lang.Override
      public boolean getEnabled() {
        return enabled_;
      }
      /**
       * <code>bool enabled = 8;</code>
       * @param value The enabled to set.
       * @return This builder for chaining.
       */
      public Builder setEnabled(boolean value) {

        enabled_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>bool enabled = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnabled() {
        bitField0_ = (bitField0_ & ~0x00000080);
        enabled_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ecommerce.UserResponse)
    }

    // @@protoc_insertion_point(class_scope:ecommerce.UserResponse)
    private static final com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse();
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserResponse>
        PARSER = new com.google.protobuf.AbstractParser<UserResponse>() {
      @java.lang.Override
      public UserResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UsersResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ecommerce.UsersResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ecommerce.UserResponse content = 1;</code>
     */
    java.util.List<com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse> 
        getContentList();
    /**
     * <code>repeated .ecommerce.UserResponse content = 1;</code>
     */
    com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse getContent(int index);
    /**
     * <code>repeated .ecommerce.UserResponse content = 1;</code>
     */
    int getContentCount();
    /**
     * <code>repeated .ecommerce.UserResponse content = 1;</code>
     */
    java.util.List<? extends com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponseOrBuilder> 
        getContentOrBuilderList();
    /**
     * <code>repeated .ecommerce.UserResponse content = 1;</code>
     */
    com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponseOrBuilder getContentOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ecommerce.UsersResponse}
   */
  public static final class UsersResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ecommerce.UsersResponse)
      UsersResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        UsersResponse.class.getName());
    }
    // Use UsersResponse.newBuilder() to construct.
    private UsersResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UsersResponse() {
      content_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_UsersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_UsersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse.class, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse.Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse> content_;
    /**
     * <code>repeated .ecommerce.UserResponse content = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse> getContentList() {
      return content_;
    }
    /**
     * <code>repeated .ecommerce.UserResponse content = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponseOrBuilder> 
        getContentOrBuilderList() {
      return content_;
    }
    /**
     * <code>repeated .ecommerce.UserResponse content = 1;</code>
     */
    @java.lang.Override
    public int getContentCount() {
      return content_.size();
    }
    /**
     * <code>repeated .ecommerce.UserResponse content = 1;</code>
     */
    @java.lang.Override
    public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse getContent(int index) {
      return content_.get(index);
    }
    /**
     * <code>repeated .ecommerce.UserResponse content = 1;</code>
     */
    @java.lang.Override
    public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponseOrBuilder getContentOrBuilder(
        int index) {
      return content_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < content_.size(); i++) {
        output.writeMessage(1, content_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < content_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, content_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse)) {
        return super.equals(obj);
      }
      com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse other = (com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse) obj;

      if (!getContentList()
          .equals(other.getContentList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getContentCount() > 0) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContentList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ecommerce.UsersResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ecommerce.UsersResponse)
        com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_UsersResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_UsersResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse.class, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse.Builder.class);
      }

      // Construct using com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (contentBuilder_ == null) {
          content_ = java.util.Collections.emptyList();
        } else {
          content_ = null;
          contentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_UsersResponse_descriptor;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse getDefaultInstanceForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse build() {
        com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse buildPartial() {
        com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse result = new com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse result) {
        if (contentBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            content_ = java.util.Collections.unmodifiableList(content_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
      }

      private void buildPartial0(com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse) {
          return mergeFrom((com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse other) {
        if (other == com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse.getDefaultInstance()) return this;
        if (contentBuilder_ == null) {
          if (!other.content_.isEmpty()) {
            if (content_.isEmpty()) {
              content_ = other.content_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContentIsMutable();
              content_.addAll(other.content_);
            }
            onChanged();
          }
        } else {
          if (!other.content_.isEmpty()) {
            if (contentBuilder_.isEmpty()) {
              contentBuilder_.dispose();
              contentBuilder_ = null;
              content_ = other.content_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contentBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getContentFieldBuilder() : null;
            } else {
              contentBuilder_.addAllMessages(other.content_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse m =
                    input.readMessage(
                        com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.parser(),
                        extensionRegistry);
                if (contentBuilder_ == null) {
                  ensureContentIsMutable();
                  content_.add(m);
                } else {
                  contentBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse> content_ =
        java.util.Collections.emptyList();
      private void ensureContentIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          content_ = new java.util.ArrayList<com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse>(content_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.Builder, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponseOrBuilder> contentBuilder_;

      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public java.util.List<com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse> getContentList() {
        if (contentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(content_);
        } else {
          return contentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public int getContentCount() {
        if (contentBuilder_ == null) {
          return content_.size();
        } else {
          return contentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse getContent(int index) {
        if (contentBuilder_ == null) {
          return content_.get(index);
        } else {
          return contentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public Builder setContent(
          int index, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.set(index, value);
          onChanged();
        } else {
          contentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public Builder setContent(
          int index, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.set(index, builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public Builder addContent(com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.add(value);
          onChanged();
        } else {
          contentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public Builder addContent(
          int index, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.add(index, value);
          onChanged();
        } else {
          contentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public Builder addContent(
          com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.add(builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public Builder addContent(
          int index, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.add(index, builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public Builder addAllContent(
          java.lang.Iterable<? extends com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse> values) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, content_);
          onChanged();
        } else {
          contentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public Builder removeContent(int index) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.remove(index);
          onChanged();
        } else {
          contentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.Builder getContentBuilder(
          int index) {
        return getContentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponseOrBuilder getContentOrBuilder(
          int index) {
        if (contentBuilder_ == null) {
          return content_.get(index);  } else {
          return contentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public java.util.List<? extends com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponseOrBuilder> 
           getContentOrBuilderList() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(content_);
        }
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.Builder addContentBuilder() {
        return getContentFieldBuilder().addBuilder(
            com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.Builder addContentBuilder(
          int index) {
        return getContentFieldBuilder().addBuilder(
            index, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .ecommerce.UserResponse content = 1;</code>
       */
      public java.util.List<com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.Builder> 
           getContentBuilderList() {
        return getContentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.Builder, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponseOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponse.Builder, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UserResponseOrBuilder>(
                  content_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ecommerce.UsersResponse)
    }

    // @@protoc_insertion_point(class_scope:ecommerce.UsersResponse)
    private static final com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse();
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UsersResponse>
        PARSER = new com.google.protobuf.AbstractParser<UsersResponse>() {
      @java.lang.Override
      public UsersResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UsersResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UsersResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.UsersResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EnabledUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ecommerce.EnabledUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool enabled = 1;</code>
     * @return The enabled.
     */
    boolean getEnabled();
  }
  /**
   * Protobuf type {@code ecommerce.EnabledUser}
   */
  public static final class EnabledUser extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ecommerce.EnabledUser)
      EnabledUserOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        EnabledUser.class.getName());
    }
    // Use EnabledUser.newBuilder() to construct.
    private EnabledUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EnabledUser() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_EnabledUser_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_EnabledUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser.class, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser.Builder.class);
    }

    public static final int ENABLED_FIELD_NUMBER = 1;
    private boolean enabled_ = false;
    /**
     * <code>bool enabled = 1;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (enabled_ != false) {
        output.writeBool(1, enabled_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (enabled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, enabled_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser)) {
        return super.equals(obj);
      }
      com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser other = (com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser) obj;

      if (getEnabled()
          != other.getEnabled()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnabled());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ecommerce.EnabledUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ecommerce.EnabledUser)
        com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_EnabledUser_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_EnabledUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser.class, com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser.Builder.class);
      }

      // Construct using com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        enabled_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.internal_static_ecommerce_EnabledUser_descriptor;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser getDefaultInstanceForType() {
        return com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser.getDefaultInstance();
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser build() {
        com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser buildPartial() {
        com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser result = new com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.enabled_ = enabled_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser) {
          return mergeFrom((com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser other) {
        if (other == com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser.getDefaultInstance()) return this;
        if (other.getEnabled() != false) {
          setEnabled(other.getEnabled());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                enabled_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean enabled_ ;
      /**
       * <code>bool enabled = 1;</code>
       * @return The enabled.
       */
      @java.lang.Override
      public boolean getEnabled() {
        return enabled_;
      }
      /**
       * <code>bool enabled = 1;</code>
       * @param value The enabled to set.
       * @return This builder for chaining.
       */
      public Builder setEnabled(boolean value) {

        enabled_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool enabled = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnabled() {
        bitField0_ = (bitField0_ & ~0x00000001);
        enabled_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ecommerce.EnabledUser)
    }

    // @@protoc_insertion_point(class_scope:ecommerce.EnabledUser)
    private static final com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser();
    }

    public static com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnabledUser>
        PARSER = new com.google.protobuf.AbstractParser<EnabledUser>() {
      @java.lang.Override
      public EnabledUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EnabledUser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnabledUser> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lkgroup.ecommerce.protobuf.userproto.UsersProtos.EnabledUser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_UserResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ecommerce_UserResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_UsersResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ecommerce_UsersResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_EnabledUser_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ecommerce_EnabledUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\tecommerce\"\215\001\n\014UserResponse" +
      "\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010username\030\003" +
      " \001(\t\022\r\n\005email\030\004 \001(\t\022\017\n\007address\030\005 \001(\t\022\r\n\005" +
      "phone\030\006 \001(\t\022\021\n\timagePath\030\007 \001(\t\022\017\n\007enable" +
      "d\030\010 \001(\010\"9\n\rUsersResponse\022(\n\007content\030\001 \003(" +
      "\0132\027.ecommerce.UserResponse\"\036\n\013EnabledUse" +
      "r\022\017\n\007enabled\030\001 \001(\010B7\n(com.lkgroup.ecomme" +
      "rce.protobuf.userprotoB\013UsersProtosb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ecommerce_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ecommerce_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ecommerce_UserResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Username", "Email", "Address", "Phone", "ImagePath", "Enabled", });
    internal_static_ecommerce_UsersResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ecommerce_UsersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ecommerce_UsersResponse_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_ecommerce_EnabledUser_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ecommerce_EnabledUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ecommerce_EnabledUser_descriptor,
        new java.lang.String[] { "Enabled", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
